### ISSUE TITLE
Run Android Studio inside Termux Proot

### ISSUE THREAD

**Issue by maleeqB** [ShivaShirsath/Ubuntu-On-Android#3]
I saw your comment [on Installing Android Emulators](https://github.com/termux/proot-distro/issues/100) under Termux-Proot issues and you mentioned Android Studio. Please I would like to ask, were you able to install Android Studio inside Termux Proot? If yes please how did you go about it please

**Comment by ShivaShirsath** [comment]
Install jdk 
```bash
sudo apt install -y openjdk-11-jdk
```
 
Download android studio tar.gz file from [official website](https://developer.android.com/studio#downloads)
Extract this file in your home `cd $HOME` directory 

`sudo tar zxvf file.tar.gz`


Then run `bash $HOME/android-studio/bin/studio.sh` this cammand

**Comment by maleeqB** [comment]
Wow ok thanks
